In [62]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt

## CS418 Data Science Final Project

### Names: Abhi Shah, Brian De Villa,  Katherine Misyutina, Matthew Jankowski

#### Dataset Topic:
Child Mortality for children under the age of 5. Compare different countries and diseases. Show differences between devloped and devloping countries.

#### Criteria:
In early April (exact date to be announced) you must submit your progress report. Your progress report must contain the following:

    1)An introduction part to your data:
        * Data spec: describe your data. Include the format and any assumptions about your data, size of the dataset
        * A link to your full data in downloadable form, you can keep your data on Google Drive, Box, DropBox, GitHub, or personal website
        * A sample of your data ( n = 10 - 50)
        * A report of your data collection process
            * How did you collect your data
            * How did you clean your data
            * Mention any difficulties you faced in the beginning steps
2) A summary of challenges and observations you have made so far. 
A brief mention of your next steps and what you plan to do with your data as you move into the analysis (If you are already in the analysis phase you can mention that as well)
Group member duties

## Cleaning GDP Dataset

Import the CSV here (CSV must be stored exactly where this .pnyb file is located)

In [63]:
df = pd.read_csv('../../../datasets/CleanedGDP/Clean_gdp.csv')

# Prints the first 5 from the data

In [64]:
def createDFRowValueForYear(myYear):
    yearData = df['Year']==myYear
    df2 = df.loc[yearData].copy()
    df2GDP = df2['GDP per Capita']
    df2GDP = df2GDP.reset_index(drop=True)
    return df2GDP

# Create unique list of Country List
countryList = df['Country'].unique()

# Year List
yearList = [2000, 2005, 2010, 2015]

# Create Empty Dataframe with same columns
newDF = pd.DataFrame(columns=['Country', 2000, 2005, 2010, 2015])

#Append country list
newDF['Country'] = countryList

for year in yearList:
    tempDF = createDFRowValueForYear(year)
    newDF[year] = tempDF

newDF

               Country          2000          2005          2010          2015
0              Albania   5668.574777   7733.006933   9927.181841  10970.452245
1            Australia  35377.729552  38928.040757  41464.040070  43923.258269
2           Bangladesh   1641.958768   1929.938743   2442.728888   3132.567540
3               Brazil  11370.970939  12298.587948  14537.567193  14702.591268
4              Burundi    754.096280    724.160012    763.831930    748.415271
5               Canada  37431.916978  40471.260525  40699.355129  43149.475837
6                Chile  14315.426057  17007.579822  19442.050315  22516.607858
7                China   3700.743648   5719.455366   9525.818483  13569.891527
8             Colombia   8308.222950   9263.730173  10900.505282  12985.383135
9   Dominican Republic   8200.378427   9011.512148  11132.552691  13395.916802
10             Ecuador   7387.615879   8607.765409   9352.344237  10749.128874
11            Ethiopia    618.242219    732.380498   1073.826295   1533.107632
12                Fiji   6673.847391   7426.778763   7352.088360   8477.644730
13             Germany  36764.562927  37703.932940  40428.721031  43937.947132
14           Guatemala   6070.720060   6269.155585   6714.063596   7292.719104
15               Haiti   1739.392520   1561.960451   1502.032711   1651.228445
16               India   2495.046633   3178.828724   4404.697005   5756.664665
17               Kenya   2132.161897   2224.031001   2476.010742   2835.996610
18              Mexico  15682.812170  15791.537031  15715.972145  16938.605406
19             Morocco   4483.808406   5361.662834   6443.253613   7296.934401
20         New Zealand  27620.472800  31351.835921  32119.215543  35309.823724
21             Nigeria   2848.150520   4149.277997   5150.158818   5670.639443
22         Philippines   4224.113226   4778.971220   5596.837288   6874.582566
23              Poland  14732.481998  17193.523732  21770.644436  25299.974348
24              Russia  14050.851335  19325.935737  23107.785221  24516.549950
25        Saudi Arabia  43071.449832  45538.497969  45421.228480  50723.712645
26              Serbia   7984.836247  10900.912414  12688.124290  13277.800117
27     Solomon Islands   1816.734783   1680.506478   1871.369352   2149.221632
28        South Africa   9538.968503  10783.194960  11887.805034  12377.659260
29              Uganda   1049.778625   1222.703216   1515.866412   1665.949905
30             Ukraine   4797.380277   7246.351027   7824.498452   7464.939834
31       United States  45986.052710  49762.237901  49374.178885  53005.636146

In [66]:
# Save Curated Dataset
newDF.to_csv ('../../../datasets/CleanedGDP/Clean_gdp2.csv', index = False)